### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by StevenBCamp** [CockpitConnect/msfs-simconnect-nodejs#3]
Nan Is installed from npm also.
Include paths are set to:
${workspaceFolder}/**
C:\Users\XXXX\git\msfs-simconnect-nodejs\**

PS C:\Users\XXXX\git\msfs-simconnect-nodejs> npm run build

> msfs-simconnect-nodejs@0.0.2 build
> node-gyp configure build --msvs_version=2019 --arch=x64

gyp info it worked if it ends with ok   
gyp info using node-gyp@7.1.2
gyp info using node@15.0.1 | win32 | x64
gyp info find Python using Python version 3.7.8 found at "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe"
gyp info find VS using VS2019 (16.7.30621.155) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"        
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\XXXX\\git\\msfs-simconnect-nodejs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\XXXX\\AppData\\Local\\node-gyp\\Cache\\15.0.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\XXXX\\AppData\\Local\\node-gyp\\Cache\\15.0.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\XXXX\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\XXXX\\git\\msfs-simconnect-nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\XXXX\\git\\msfs-simconnect-nodejs\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  addon.cc
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(190,103): error C2661: 'v8::Object::Set': no overloaded function takes 2 argumen
ts [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(209,82): error C2440: 'initializing': cannot convert from 'v8::MaybeLocal<v8::St 
ring>' to 'v8::Local<v8::String>' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(209,82): message : No constructor could take the source type, or constructor ove 
rload resolution was ambiguous [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(211,4): warning C4530: C++ exception handler used, but unwind semantics are not 
enabled. Specify /EHsc [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(213,32): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(217,72): error C2440: 'initializing': cannot convert from 'v8::MaybeLocal<v8::St 
ring>' to 'v8::Local<v8::String>' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(217,72): message : No constructor could take the source type, or constructor ove 
rload resolution was ambiguous [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(218,32): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(229,99): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(237,45): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(258,40): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(282,42): error C2440: 'initializing': cannot convert from 'v8::MaybeLocal<v8::St 
ring>' to 'v8::Local<v8::Value>' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(282,42): message : No constructor could take the source type, or constructor ove 
rload resolution was ambiguous [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(284,15): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(295,41): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(303,97): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(304,91): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(305,89): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(306,79): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(307,95): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(308,136): error C2661: 'v8::Object::Set': no overloaded function takes 2 argumen 
ts [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(312,40): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(320,67): error C2440: 'initializing': cannot convert from 'v8::MaybeLocal<v8::St 
ring>' to 'v8::Local<v8::Value>' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(320,67): message : No constructor could take the source type, or constructor ove 
rload resolution was ambiguous [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(322,42): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(336,47): error C2440: 'initializing': cannot convert from 'v8::MaybeLocal<v8::St 
ring>' to 'v8::Local<v8::Value>' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(336,47): message : No constructor could take the source type, or constructor ove 
rload resolution was ambiguous [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(338,35): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(346,91): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(347,86): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(348,89): error C2661: 'v8::Object::Set': no overloaded function takes 2 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(351,35): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(357,35): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users 
\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(658,73): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(658,46): error C2672: 'v8::Local<v8::Array>::Cast': no matching overloaded funct 
ion found [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(666,58): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(666,92): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Va 
lue &)': cannot convert argument 1 from 'v8::Isolate *' to 'const v8::String::Utf8Value &' [C:\Users\XXXX\git\msfs-simconnect-nodejs\b 
uild\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(666,92): message : Reason: cannot convert from 'v8::Isolate *' to 'const v8::Str 
ing::Utf8Value' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(666,92): message : No constructor could take the source type, or constructor ove 
rload resolution was ambiguous [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\AppData\Local\node-gyp\Cache\15.0.1\include\node\v8.h(3340,5): message : see declaration of 'v8::String::Utf8Value::Utf8 
Value' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(670,8): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments 
 [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(672,59): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(672,93): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Va 
lue &)': cannot convert argument 1 from 'v8::Isolate *' to 'const v8::String::Utf8Value &' [C:\Users\XXXX\git\msfs-simconnect-nodejs\b 
uild\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(672,93): message : Reason: cannot convert from 'v8::Isolate *' to 'const v8::Str 
ing::Utf8Value' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(672,93): message : No constructor could take the source type, or constructor ove 
rload resolution was ambiguous [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\AppData\Local\node-gyp\Cache\15.0.1\include\node\v8.h(3340,5): message : see declaration of 'v8::String::Utf8Value::Utf8 
Value' [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(691,26): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(702,28): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(712,28): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(751,91): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(752,91): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(753,92): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(754,92): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(755,89): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(756,90): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(757,91): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
C:\Users\XXXX\git\msfs-simconnect-nodejs\src\addon.cc(758,91): error C2661: 'v8::Object::Get': no overloaded function takes 1 argument 
s [C:\Users\XXXX\git\msfs-simconnect-nodejs\build\msfs-simconnect-nodejs.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--msvs_version=2019" "--arch=x64"
gyp ERR! cwd C:\Users\XXXX\git\msfs-simconnect-nodejs
gyp ERR! node -v v15.0.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
npm ERR! code 1
npm ERR! path C:\Users\XXXX\git\msfs-simconnect-nodejs
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "node-gyp configure build --msvs_version=2019 --arch=x64"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Local\npm-cache\_logs\2020-10-29T01_15_36_904Z-debug.log
PS C:\Users\XXXX\git\msfs-simconnect-nodejs>

===========================config.gypi file====================================
# Do not edit. File was generated by node-gyp's "configure" step
{
  "target_defaults": {
    "cflags": [],
    "default_configuration": "Release",
    "defines": [],
    "include_dirs": [],
    "libraries": [],
    "msbuild_toolset": "v142",
    "msvs_windows_target_platform_version": "10.0.18362.0"
  },
  "variables": {
    "asan": 0,
    "coverage": "false",
    "dcheck_always_on": 0,
    "debug_nghttp2": "false",
    "debug_node": "false",
    "enable_lto": "false",
    "enable_pgo_generate": "false",
    "enable_pgo_use": "false",
    "error_on_warn": "false",
    "experimental_quic": "false",
    "force_dynamic_crt": 0,
    "host_arch": "x64",
    "icu_data_in": "..\\..\\deps\\icu-tmp\\icudt67l.dat",
    "icu_endianness": "l",
    "icu_gyp_path": "tools/icu/icu-generic.gyp",
    "icu_path": "deps/icu-small",
    "icu_small": "false",
    "icu_ver_major": "67",
    "is_debug": 0,
    "napi_build_version": "7",
    "nasm_version": "2.14",
    "node_byteorder": "little",
    "node_debug_lib": "false",
    "node_enable_d8": "false",
    "node_install_npm": "true",
    "node_module_version": 88,
    "node_no_browser_globals": "false",
    "node_prefix": "/usr/local",
    "node_release_urlbase": "https://nodejs.org/download/release/",
    "node_shared": "false",
    "node_shared_brotli": "false",
    "node_shared_cares": "false",
    "node_shared_http_parser": "false",
    "node_shared_libuv": "false",
    "node_shared_nghttp2": "false",
    "node_shared_openssl": "false",
    "node_shared_zlib": "false",
    "node_tag": "",
    "node_target_type": "executable",
    "node_use_bundled_v8": "true",
    "node_use_dtrace": "false",
    "node_use_etw": "true",
    "node_use_node_code_cache": "true",
    "node_use_node_snapshot": "true",
    "node_use_openssl": "true",
    "node_use_v8_platform": "true",
    "node_with_ltcg": "true",
    "node_without_node_options": "false",
    "openssl_fips": "",
    "openssl_is_fips": "false",
    "ossfuzz": "false",
    "shlib_suffix": "so.88",
    "target_arch": "x64",
    "v8_enable_31bit_smis_on_64bit_arch": 0,
    "v8_enable_gdbjit": 0,
    "v8_enable_i18n_support": 1,
    "v8_enable_inspector": 1,
    "v8_enable_lite_mode": 0,
    "v8_enable_object_print": 1,
    "v8_enable_pointer_compression": 0,
    "v8_no_strict_aliasing": 1,
    "v8_optimized_debug": 1,
    "v8_promise_internal_field_count": 1,
    "v8_random_seed": 0,
    "v8_trace_maps": 0,
    "v8_use_siphash": 1,
    "want_separate_host_toolset": 0,
    "nodedir": "C:\\Users\\XXXX\\AppData\\Local\\node-gyp\\Cache\\15.0.1",
    "standalone_static_library": 1,
    "msbuild_path": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\MSBuild\\Current\\Bin\\MSBuild.exe",
    "cache": "C:\\Users\\XXXX\\AppData\\Local\\npm-cache",
    "globalconfig": "C:\\Users\\XXXX\\AppData\\Roaming\\npm\\etc\\npmrc",
    "init.module": "C:\\Users\\XXXX\\.npm-init.js",
    "init_module": "C:\\Users\\XXXX\\.npm-init.js",
    "metrics_registry": "https://registry.npmjs.org/",
    "node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
    "prefix": "C:\\Users\\XXXX\\AppData\\Roaming\\npm",
    "userconfig": "C:\\Users\\XXXX\\.npmrc",
    "user_agent": "npm/7.0.3 node/v15.0.1 win32 x64"
  }
}

Any assistance would be greatly appreciated.
Thank you,
~Steve

**Comment by StevenBCamp** [comment]
So the issue appears to be the Node Version. Can you put the current version you are using in the readme?

**Comment by CockpitConnect** [comment]
@StevenBCamp Thanks you for your comment. You were using Node version v15.0.1, right? The project was built on v12, so I added that to the readme. I'll check for Node v14 (LTS) support soon.

**Comment by StevenBCamp** [comment]
Node version v12.19.0 compiles but has some warnings for declared deprecated 'V8::Object:Get'.
